# Generated by Django 5.0.6 on 2026-02-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='last_updated',
            new_name='last_signal_time',
        ),
        migrations.AddField(
            model_name='vessel',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VesselEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STOPPED', 'Stopped'), ('ROUTE_CHANGED', 'Route Changed'), ('AIS_LOST', 'AIS Signal Lost'), ('POSITION_CHANGED', 'Position Changed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vessel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vesselevent')),
            ],
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vessel')),
            ],
            options={
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
