# Generated by Django 6.0.3 on 2026-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_notification_event_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyzone',
            name='severity',
            field=models.CharField(default='SAFE', help_text='SAFE, MEDIUM, HIGH', max_length=20),
        ),
        migrations.AddField(
            model_name='safetyzone',
            name='zone_type',
            field=models.CharField(default='GENERAL', help_text='e.g. STORM, PIRACY, ACCIDENT', max_length=50),
        ),
    ]
