# Generated by Django 5.0.6 on 2026-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0007_update_demo_vessel_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
