# Generated by Django 5.0.6 on 2026-04-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0008_vessel_created_at_vessel_operator_vessel_owner_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['imo_number'], name='vessels_ves_imo_num_1c2106_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type'], name='vessels_ves_vessel__b7df03_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['flag'], name='vessels_ves_flag_9d8886_idx'),
        ),
    ]
