# Generated by Django 6.0.3 on 2026-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('STOPPED', 'Vessel Stopped'), ('MOVED', 'Vessel Started Moving'), ('ROUTE_CHANGED', 'Vessel Route Changed'), ('PORT_ENTERED', 'Vessel Entered Port'), ('PORT_DEPARTED', 'Vessel Departed Port'), ('STORM_ALERT', 'Storm Detection'), ('CYCLONE_ALERT', 'Cyclone Detection'), ('PIRACY_ZONE_ALERT', 'Piracy Zone Detection'), ('SAFETY_ALERT', 'General Safety Alert'), ('CONGESTION_ALERT', 'Port Congestion Alert')], max_length=100),
        ),
    ]
