# Generated by Django 4.2.28 on 2026-02-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_vessel_operator_alter_vessel_cargo_type_and_more'),
        ('notifications', '0002_alter_notification_options_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='vessels.vesselevent'),
        ),
    ]
