# Generated by Django 4.2.28 on 2026-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_vessel'),
    ]

    operations = [
    ]
