# Generated by Django 4.2.28 on 2026-03-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_notificatio_user_id_c291d5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_is_read_9edb86_idx',
        ),
    ]
