# Generated by Django 4.2.28 on 2026-02-18 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_position_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_position_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
