# Generated by Django 6.0.2 on 2026-02-23 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0004_remove_vessel_type_vessel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_events', to='vessels.vessel')),
            ],
            options={
                'indexes': [models.Index(fields=['vessel', '-timestamp'], name='idx_safety_vessel_ts_desc'), models.Index(fields=['event_type', '-timestamp'], name='idx_safety_type_ts_desc')],
            },
        ),
    ]
