# Generated by Django 6.0.3 on 2026-03-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_externalsafetydata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externalsafetydata',
            index=models.Index(fields=['source', 'fetched_at'], name='safety_exte_source_3a8349_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsafetydata',
            index=models.Index(fields=['zone_type'], name='safety_exte_zone_ty_1875cd_idx'),
        ),
    ]
