# Generated by Django 6.0.3 on 2026-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_externalsafetydata_safety_exte_source_3a8349_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', '-created_at'], name='idx_api_log_source_created'), models.Index(fields=['status'], name='idx_api_log_status')],
            },
        ),
    ]
