# Generated by Django 6.0.3 on 2026-03-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='last_update',
            new_name='last_analytics_update',
        ),
    ]
