# Generated by Django 6.0.3 on 2026-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_porttraffichistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['congestion_score'], name='idx_port_congestion'),
        ),
    ]
