# Generated by Django 6.0.2 on 2026-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_rename_last_updated_vessel_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='name',
        ),
        migrations.AddField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
