# Generated by Django 6.0.3 on 2026-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_remove_vessel_type_vessel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type', 'flag', '-last_update'], name='idx_vessel_type_flag_lu_desc'),
        ),
    ]
