# Generated by Django 6.0.3 on 2026-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_alter_vessel_id_alter_vesselposition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
