# Generated by Django 6.0.3 on 2026-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0007_alter_vessel_id_alter_vesselposition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('in_port', 'In Port'), ('anchored', 'Anchored')], default='in_transit', max_length=20),
        ),
    ]
