# Generated by Django 5.0.6 on 2026-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_seed_dummy_replay_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voyagehistory',
            index=models.Index(fields=['voyage', 'timestamp'], name='idx_voyage_time'),
        ),
    ]
