# Generated by Django 5.0.6 on 2026-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_voyagehistory_idx_voyage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='destination_port_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='origin_port_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
