# Generated by Django 4.2.28 on 2026-02-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_phone_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_email_verified',
        ),
    ]
