# Generated by Django 4.2.28 on 2026-03-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_departures', to='ports.port')),
                ('port_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_arrivals', to='ports.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-departure_time'],
                'indexes': [models.Index(fields=['vessel', 'status'], name='voyages_voy_vessel__a079a2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='voyage',
            constraint=models.CheckConstraint(check=models.Q(('arrival_time__gte', models.F('departure_time')), ('arrival_time__isnull', True), _connector='OR'), name='arrival_after_departure'),
        ),
    ]
