# Generated by Django 6.0.3 on 2026-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_alter_porttraffichistory_timestamp'),
        ('vessels', '0007_alter_vessel_id_alter_vesselposition_id'),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['vessel', 'departure_time'], name='voyages_voy_vessel__0a287a_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['status'], name='voyages_voy_status_3bb46e_idx'),
        ),
    ]
