# Generated by Django 4.2.28 on 2026-02-18 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_alter_vessel_options_vessel_created_at_and_more'),
        ('ports', '0002_alter_port_options_port_created_at_and_more'),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voyage',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AddField(
            model_name='voyage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voyage',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='port_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_departures', to='ports.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='port_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_arrivals', to='ports.port'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='vessels.vessel'),
        ),
    ]
