# Generated by Django 6.0.3 on 2026-03-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0006_port_city_port_latitude_port_longitude_and_more'),
        ('vessels', '0010_vesselalert'),
        ('voyages', '0002_voyage_voyages_voy_vessel__0a287a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('distance_nm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('port_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_departures', to='ports.port')),
                ('port_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_arrivals', to='ports.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_history', to='vessels.vessel')),
            ],
        ),
    ]
