# Generated by Django 4.2.28 on 2026-02-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_alter_voyage_options_voyage_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['vessel', 'status'], name='voyages_voy_vessel__a079a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='voyage',
            constraint=models.CheckConstraint(check=models.Q(('arrival_time__gte', models.F('departure_time')), ('arrival_time__isnull', True), _connector='OR'), name='arrival_after_departure'),
        ),
    ]
