# Generated by Django 5.0.6 on 2026-02-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_failed_login_attempts_user_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
