# Generated by Django 6.0.3 on 2026-03-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_safetyzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=0)),
                ('severity', models.CharField(default='medium', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_external_source_id')],
            },
        ),
    ]
