# Generated by Django 4.2.28 on 2026-03-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('congestion_score', models.FloatField()),
                ('avg_wait_time', models.FloatField()),
                ('arrivals', models.PositiveIntegerField()),
                ('departures', models.PositiveIntegerField()),
                ('last_update', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
