# Generated by Django 4.2.28 on 2026-03-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('congestion_score', models.FloatField()),
                ('avg_wait_time', models.FloatField()),
                ('arrivals', models.PositiveIntegerField()),
                ('departures', models.PositiveIntegerField()),
                ('last_update', models.DateTimeField(db_index=True)),
                ('last_analytics_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortTrafficHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('arrivals', models.PositiveIntegerField()),
                ('departures', models.PositiveIntegerField()),
                ('congestion_score', models.FloatField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_history', to='ports.port')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['name'], name='ports_port_name_8ef3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['country'], name='ports_port_country_d703b5_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['last_update'], name='ports_port_last_up_4bde7e_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['congestion_score'], name='ports_port_congest_ec28e9_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['country', 'congestion_score'], name='ports_port_country_566118_idx'),
        ),
        migrations.AddIndex(
            model_name='porttraffichistory',
            index=models.Index(fields=['port', 'timestamp'], name='ports_portt_port_id_0c13bf_idx'),
        ),
    ]
