# Generated by Django 4.2.28 on 2026-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='arrivals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='avg_wait_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='port',
            name='congestion_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='port',
            name='departures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
