# Generated by Django 4.2.28 on 2026-02-18 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='port',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='arrivals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='departures',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
