# Generated by Django 4.2.28 on 2026-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='last_update',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['name'], name='ports_port_name_8ef3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['country'], name='ports_port_country_d703b5_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['last_update'], name='ports_port_last_up_4bde7e_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['congestion_score'], name='ports_port_congest_ec28e9_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['country', 'congestion_score'], name='ports_port_country_566118_idx'),
        ),
    ]
