# Generated by Django 6.0.3 on 2026-03-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_rename_last_update_port_last_analytics_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortTrafficHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('arrivals', models.IntegerField(default=0)),
                ('departures', models.IntegerField(default=0)),
                ('congestion_score', models.FloatField(default=0)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_history', to='ports.port')),
            ],
            options={
                'indexes': [models.Index(fields=['port', 'timestamp'], name='idx_porttraffic_port_ts')],
            },
        ),
    ]
