# Generated by Django 4.2.28 on 2026-03-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_alter_port_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='last_analytics_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PortTrafficHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('arrivals', models.PositiveIntegerField()),
                ('departures', models.PositiveIntegerField()),
                ('congestion_score', models.FloatField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_history', to='ports.port')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['port', 'timestamp'], name='ports_portt_port_id_0c13bf_idx')],
            },
        ),
    ]
