# Generated by Django 4.2.28 on 2026-03-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_alter_port_options_port_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('raw_data', models.JSONField()),
                ('checksum', models.CharField(help_text='SHA-256 / MD5 hash of raw_data to prevent duplicate inserts', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'External Safety Data',
                'verbose_name_plural': 'External Safety Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortTrafficHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('arrivals', models.PositiveIntegerField(default=0)),
                ('departures', models.PositiveIntegerField(default=0)),
                ('congestion_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('storm', 'Storm / Severe Weather'), ('piracy', 'Piracy Zone'), ('accident', 'Accident Zone'), ('restricted', 'Restricted Area'), ('other', 'Other Hazard')], db_index=True, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=50.0, help_text='Radius of the safety zone in nautical miles')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='port',
            name='last_analytics_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='arrivals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='avg_wait_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='port',
            name='congestion_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='port',
            name='departures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='port',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['congestion_score'], name='port_congestion_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['country'], name='port_country_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyzone',
            index=models.Index(fields=['zone_type'], name='safety_zone_type_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyzone',
            index=models.Index(fields=['expires_at'], name='safety_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyzone',
            index=models.Index(fields=['zone_type', 'expires_at'], name='safety_zone_expires_idx'),
        ),
        migrations.AddField(
            model_name='porttraffichistory',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_history', to='ports.port'),
        ),
        migrations.AddIndex(
            model_name='externalsafetydata',
            index=models.Index(fields=['source'], name='ext_source_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsafetydata',
            index=models.Index(fields=['status'], name='ext_status_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsafetydata',
            index=models.Index(fields=['created_at'], name='ext_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='porttraffichistory',
            index=models.Index(fields=['port'], name='traffic_port_idx'),
        ),
        migrations.AddIndex(
            model_name='porttraffichistory',
            index=models.Index(fields=['timestamp'], name='traffic_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='porttraffichistory',
            index=models.Index(fields=['port', 'timestamp'], name='traffic_port_ts_idx'),
        ),
    ]
