# Generated by Django 6.0.3 on 2026-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0004_port_idx_port_congestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porttraffichistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
