# Generated by Django 6.0.3 on 2026-03-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_alter_porttraffichistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='number_of_berths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='port_type',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('container', 'Container'), ('oil', 'Oil'), ('mixed', 'Mixed')], default='cargo', max_length=20),
        ),
        migrations.AddField(
            model_name='port',
            name='unlocode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
