version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: maritime_postgres
    restart: always
    environment:
      POSTGRES_DB: maritime_db
      POSTGRES_USER: maritime_user
      POSTGRES_PASSWORD: maritime_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: maritime_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: maritime_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_NAME: maritime_db
      DB_USER: maritime_user
      DB_PASSWORD: maritime_pass
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: maritime_celery
    command: celery -A core worker --loglevel=info
    volumes:
      - ..:/app
    depends_on:
      - postgres
      - redis
    environment:
      DB_NAME: maritime_db
      DB_USER: maritime_user
      DB_PASSWORD: maritime_pass
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres_data:
