# Generated by Django 6.0.2 on 2026-02-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(choices=[('Cargo', 'Cargo'), ('Tanker', 'Tanker'), ('Passenger', 'Passenger')], max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('current_port', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
