# Generated by Django 4.2.28 on 2026-03-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSafetyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('unique_identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('piracy', 'Piracy Zone'), ('storm', 'Storm / Severe Weather'), ('accident', 'Maritime Accident'), ('restricted', 'Restricted Area'), ('other', 'Other Hazard')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_nm', models.FloatField(default=50.0)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active_from'],
            },
        ),
        migrations.CreateModel(
            name='SafetyZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('severity', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('vessel_type', models.CharField(db_index=True, default='Unknown', max_length=50)),
                ('flag', models.CharField(db_index=True, max_length=50)),
                ('cargo_type', models.CharField(db_index=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('last_position_lat', models.FloatField(blank=True, null=True)),
                ('last_position_lon', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, db_index=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VesselEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('piracy', 'Piracy'), ('accident', 'Accident'), ('weather', 'Weather Alert'), ('port_delay', 'Port Delay'), ('inspection', 'Inspection'), ('stopped', 'Stopped'), ('underway', 'Underway'), ('route_changed', 'Route Changed'), ('entered_port', 'Entered Port'), ('ais_lost', 'AIS Signal Lost'), ('other', 'Other')], db_index=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['imo_number'], name='vessels_ves_imo_num_1c2106_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type'], name='vessels_ves_vessel__b7df03_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['flag'], name='vessels_ves_flag_9d8886_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['last_update'], name='vessels_ves_last_up_382a69_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['destination'], name='vessels_ves_destina_6af475_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['speed'], name='vessels_ves_speed_2d299b_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['last_update', 'destination'], name='vessels_ves_last_up_de8b44_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type', 'flag'], name='vessels_ves_vessel__3f084a_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyzones',
            index=models.Index(fields=['zone_type', 'expires_at'], name='vessels_saf_zone_ty_ec8290_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['event_type', 'is_active'], name='vessels_saf_event_t_9a0e83_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['severity', 'is_active'], name='vessels_saf_severit_a69bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['user'], name='vessels_ves_user_id_b54b94_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['vessel'], name='vessels_ves_vessel__8d858d_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['user', 'vessel'], name='vessels_ves_user_id_6d6a34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vesselsubscription',
            unique_together={('user', 'vessel')},
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['vessel', 'timestamp'], name='vessels_ves_vessel__cdde01_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['vessel'], name='vessels_ves_vessel__2f352a_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['timestamp'], name='vessels_ves_timesta_39af96_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['event_type'], name='vessels_ves_event_t_0f4a0b_idx'),
        ),
    ]
