# Generated by Django 4.2.28 on 2026-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=50)),
                ('cargo_type', models.CharField(max_length=50)),
                ('last_position_lat', models.FloatField(null=True)),
                ('last_position_lon', models.FloatField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
            ],
        ),
    ]
