# Generated by Django 4.2.28 on 2026-03-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vessel', 'timestamp'], name='idx_vessel_time'), models.Index(fields=['vessel'], name='vessels_ves_vessel__1533bc_idx')],
            },
        ),
    ]
