# Generated by Django 6.0.2 on 2026-02-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='last_updated',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='current_port',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='vessel_type',
        ),
        migrations.AddField(
            model_name='vessel',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='last_position_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='last_position_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VesselPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='vessels.vessel')),
            ],
        ),
    ]
