# Generated by Django 4.2.28 on 2026-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_vesselposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
    ]
