# Generated by Django 4.2.28 on 2026-02-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vessels', '0002_alter_vessel_options_vessel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cargo_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='flag',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='VesselEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('piracy', 'Piracy'), ('accident', 'Accident'), ('weather', 'Weather Alert'), ('port_delay', 'Port Delay'), ('inspection', 'Inspection'), ('other', 'Other')], db_index=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VesselSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vessel')},
            },
        ),
    ]
