# Generated by Django 6.0.2 on 2026-02-23 17:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_remove_vessel_name_vessel_mmsi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='type',
        ),
        migrations.AddField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessel',
            name='destination',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vessel',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='vessel_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='cargo_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='flag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(db_index=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_position_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_position_lon',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='last_update',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='vesselposition',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['imo_number'], name='idx_vessel_imo'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['mmsi'], name='idx_vessel_mmsi'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type'], name='idx_vessel_type'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['flag'], name='idx_vessel_flag'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['destination'], name='idx_vessel_destination'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['last_update'], name='idx_vessel_last_update'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['-last_update'], name='idx_vessel_last_update_desc'),
        ),
        migrations.AddIndex(
            model_name='vesselposition',
            index=models.Index(fields=['vessel', '-timestamp'], name='idx_pos_vessel_ts_desc'),
        ),
        migrations.AddIndex(
            model_name='vesselposition',
            index=models.Index(fields=['-timestamp'], name='idx_pos_ts_desc'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('last_position_lat__gte', -90.0), ('last_position_lat__lte', 90.0)), ('last_position_lat__isnull', True), _connector='OR'), name='chk_vessel_lat_valid'),
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('last_position_lon__gte', -180.0), ('last_position_lon__lte', 180.0)), ('last_position_lon__isnull', True), _connector='OR'), name='chk_vessel_lon_valid'),
        ),
    ]
