# Generated by Django 4.2.28 on 2026-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_vessel_operator_alter_vessel_cargo_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('piracy', 'Piracy Zone'), ('storm', 'Storm / Severe Weather'), ('accident', 'Maritime Accident'), ('restricted', 'Restricted Area'), ('other', 'Other Hazard')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_nm', models.FloatField(default=50.0)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active_from'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='vessels_saf_event_t_9a0e83_idx'), models.Index(fields=['severity', 'is_active'], name='vessels_saf_severit_a69bb4_idx')],
            },
        ),
    ]
