# Generated by Django 4.2.28 on 2026-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_safetyevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='type',
            new_name='vessel_type',
        ),
        migrations.AddField(
            model_name='vessel',
            name='destination',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vesselevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vesselevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vesselevent',
            name='event_type',
            field=models.CharField(choices=[('piracy', 'Piracy'), ('accident', 'Accident'), ('weather', 'Weather Alert'), ('port_delay', 'Port Delay'), ('inspection', 'Inspection'), ('stopped', 'Stopped'), ('underway', 'Underway'), ('route_changed', 'Route Changed'), ('entered_port', 'Entered Port'), ('ais_lost', 'AIS Signal Lost'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['imo_number'], name='vessels_ves_imo_num_1c2106_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type'], name='vessels_ves_vessel__b7df03_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['flag'], name='vessels_ves_flag_9d8886_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['last_update'], name='vessels_ves_last_up_382a69_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['destination'], name='vessels_ves_destina_6af475_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['speed'], name='vessels_ves_speed_2d299b_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['last_update', 'destination'], name='vessels_ves_last_up_de8b44_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type', 'flag'], name='vessels_ves_vessel__3f084a_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['vessel', 'timestamp'], name='vessels_ves_vessel__cdde01_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['vessel'], name='vessels_ves_vessel__2f352a_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['timestamp'], name='vessels_ves_timesta_39af96_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselevent',
            index=models.Index(fields=['event_type'], name='vessels_ves_event_t_0f4a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['user'], name='vessels_ves_user_id_b54b94_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['vessel'], name='vessels_ves_vessel__8d858d_idx'),
        ),
        migrations.AddIndex(
            model_name='vesselsubscription',
            index=models.Index(fields=['user', 'vessel'], name='vessels_ves_user_id_6d6a34_idx'),
        ),
    ]
