# Generated by Django 4.2.28 on 2026-03-05 09:34

from django.db import migrations, models
# done

class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_externalsafetydata_safetyzones'),
    ]

    operations = [
    ]
