# Generated by Django 4.2.28 on 2026-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0005_remove_vessel_type_vessel_destination_vessel_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselevent',
            name='event_type',
            field=models.CharField(choices=[('piracy', 'Piracy'), ('accident', 'Accident'), ('weather', 'Weather Alert'), ('port_delay', 'Port Delay'), ('inspection', 'Inspection'), ('Stopped', 'Stopped'), ('Underway', 'Underway'), ('Route Changed', 'Route Changed'), ('entered_port', 'Entered Port'), ('ais_lost', 'AIS Signal Lost'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
