# Generated by Django 4.2.28 on 2026-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0005_vessel_destination_vessel_heading_vessel_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='destination',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vesselevent',
            name='event_type',
            field=models.CharField(choices=[('piracy', 'Piracy'), ('accident', 'Accident'), ('weather', 'Weather Alert'), ('port_delay', 'Port Delay'), ('inspection', 'Inspection'), ('stopped', 'Stopped'), ('underway', 'Underway'), ('route_changed', 'Route Changed'), ('entered_port', 'Entered Port'), ('ais_lost', 'AIS Signal Lost'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
