# Generated by Django 4.2.28 on 2026-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_alter_vessel_destination_alter_vessel_speed_and_more'),
    ]

    operations = [
    ]
