# Generated by Django 4.2.28 on 2026-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_alter_vessel_destination_alter_vessel_speed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vessel',
            name='vessels_ves_type_2d352a_idx',
        ),
        migrations.RemoveIndex(
            model_name='vessel',
            name='vessels_ves_type_f46f01_idx',
        ),
        migrations.RenameField(
            model_name='vessel',
            old_name='type',
            new_name='vessel_type',
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type'], name='vessels_ves_vessel__b7df03_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_type', 'flag'], name='vessels_ves_vessel__3f084a_idx'),
        ),
    ]
