# Generated by Django 4.2.28 on 2026-03-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_alter_vesselevent_event_type'),
        ('vessels', '0007_remove_vessel_vessels_ves_type_2d352a_idx_and_more'),
    ]

    operations = [
    ]
