# Generated by Django 6.0.3 on 2026-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_alter_porttraffichistory_timestamp'),
        ('vessels', '0008_vessel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='ports.port')),
                ('origin_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origin', to='ports.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='vessels.vessel')),
            ],
        ),
    ]
