# Generated by Django 6.0.3 on 2026-03-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0009_vesselroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('weather', 'Weather Alert'), ('piracy', 'Piracy Alert'), ('delay', 'Delay'), ('safety', 'Safety Warning')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vessels.vessel')),
            ],
        ),
    ]
