# Generated by Django 4.2.28 on 2026-02-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('port_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_port', to='ports.port')),
                ('port_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_port', to='ports.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vessel')),
            ],
        ),
    ]
