# Generated by Django 6.0.3 on 2026-03-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_event_event_type'),
        ('vessels', '0007_alter_vessel_id_alter_vesselposition_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['vessel', 'timestamp'], name='notificatio_vessel__3b83e2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='notificatio_event_t_b6505c_idx'),
        ),
    ]
