# Generated by Django 6.0.2 on 2026-02-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
        ('vessels', '0004_remove_vessel_type_vessel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('port_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_from', to='ports.port')),
                ('port_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_to', to='ports.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='vessels.vessel')),
            ],
        ),
    ]
